#cloud-config
users:
  - name: ${TARGET_USER}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in split("\n", SSH_KEYS) ~}
%{ if key != "" ~}
      - ${key}
%{ endif ~}
%{ endfor ~}

#lsblk

packages:
  - net-tools
  - nfs-common
  - nfs-kernel-server
  - sysstat
  - mdadm
  - util-linux
  - wget
  - curl

package_upgrade: true

write_files:
  - path: /tmp/setup_raid.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # set -euo pipefail

      # Configuration from Terraform
      RAID_LEVEL="${RAID_LEVEL}"
      BLOCK_VOLUME_COUNT=${BLOCK_VOLUME_COUNT}
      TARGET_USER="${TARGET_USER}"
      
      echo "Starting RAID setup with level: $RAID_LEVEL and $BLOCK_VOLUME_COUNT devices"
      
      # Define minimum devices required for each RAID level
      case "$RAID_LEVEL" in
        "raid-0") MIN_DEVICES=2 ;;
        "raid-5") MIN_DEVICES=3 ;;
        "raid-6") MIN_DEVICES=4 ;;
        *)
          echo "ERROR: Invalid RAID level '$RAID_LEVEL'"
          exit 1
          ;;
      esac
      
      # Validate device count
      if [ "$BLOCK_VOLUME_COUNT" -lt "$MIN_DEVICES" ]; then
          echo "ERROR: RAID $RAID_LEVEL requires at least $MIN_DEVICES devices, got $BLOCK_VOLUME_COUNT"
          exit 1
      fi
      
      # Wait for all volumes to be attached
      echo "Waiting for $BLOCK_VOLUME_COUNT data volumes..."
      while true; do
          # Count non-boot block devices
          SCSI_COUNT=$(compgen -G "/dev/sd[b-z]" | wc -l )
          NVME_COUNT=$(compgen -G "/dev/nvme[1-9]n[0-9]" | wc -l )

          TOTAL_COUNT=$((SCSI_COUNT + NVME_COUNT))
          
          if [ "$TOTAL_COUNT" -ge "$BLOCK_VOLUME_COUNT" ]; then
              echo "Found $TOTAL_COUNT data volumes"
              break
          fi
          
          echo "Found $TOTAL_COUNT of $BLOCK_VOLUME_COUNT required volumes..."
          sleep 10
      done
      
      # Get available devices (excluding boot device)
      BOOT_DEVICE=$(df / | tail -1 | awk '{print $1}' | sed 's/[0-9]*$//')
      echo "Boot device: $BOOT_DEVICE"
      
      # Collect RAID devices
      RAID_DEVICES=()
      
      # Add SCSI devices
      for dev in /dev/sd[b-z]; do
          if [ -e "$dev" ] && [[ "$dev" != "$BOOT_DEVICE" ]]; then
              if ! mountpoint -q "$dev" 2>/dev/null && ! grep -qs "$dev" /proc/mounts; then
                  RAID_DEVICES+=("$dev")
              fi
          fi
      done
      
      # Add NVMe devices  
      for dev in /dev/nvme[1-9]n[0-9]; do
          if [ -e "$dev" ] && [[ "$dev" != "$BOOT_DEVICE" ]]; then
              if ! mountpoint -q "$dev" 2>/dev/null && ! grep -qs "$dev" /proc/mounts; then
                  RAID_DEVICES+=("$dev")
              fi
          fi
      done
      
      echo "RAID devices: $${RAID_DEVICES[*]}"
      
      # Prepare devices
      for dev in "$${RAID_DEVICES[@]}"; do
          echo "Preparing $dev..."
          wipefs -a "$dev" || true
          mdadm --zero-superblock "$dev" 2>/dev/null || true
      done
      
      # Create RAID array
      case "$RAID_LEVEL" in
        "raid-0")
          raid_opts="--level=0 --raid-devices=$BLOCK_VOLUME_COUNT"
          ;;
        "raid-5")
          raid_opts="--level=5 --raid-devices=$BLOCK_VOLUME_COUNT"
          ;;
        "raid-6") 
          raid_opts="--level=6 --raid-devices=$BLOCK_VOLUME_COUNT"
          ;;
      esac
      
      echo "Creating $RAID_LEVEL array..."
      yes | mdadm --create --verbose /dev/md0 $raid_opts --force "$${RAID_DEVICES[@]}"
      
      # Wait for RAID to be ready
      mdadm --wait /dev/md0
      
      # Create filesystem
      echo "Creating XFS filesystem..."
      mkfs.xfs -f /dev/md0
      
      # Mount
      mkdir -p /hsvol1
      echo "/dev/md0 /hsvol1 xfs defaults,nofail,noatime 0 0" >> /etc/fstab
      systemctl daemon-reload
      mount /hsvol1
      chmod 777 /hsvol1
      
      # Setup NFS
      echo "/hsvol1 *(rw,sync,no_root_squash,no_subtree_check)" >> /etc/exports
      systemctl enable nfs-kernel-server rpcbind
      systemctl start rpcbind nfs-kernel-server
      
      # Save RAID configuration
      mdadm --detail --scan >> /etc/mdadm/mdadm.conf
      update-initramfs -u
      
      # Create info file
      cat > /home/$TARGET_USER/oci-storage-info.txt << EOFINFO
      === OCI Storage Server Configuration ===
      Date: $(date)
      RAID Level: $RAID_LEVEL
      Devices: $${RAID_DEVICES[*]}
      Mount Point: /hsvol1
      Filesystem: XFS
      NFS Export: /hsvol1
      EOFINFO
      
      chown $TARGET_USER:$TARGET_USER /home/$TARGET_USER/oci-storage-info.txt
      
      echo "RAID setup complete!"

runcmd:
  - /tmp/setup_raid.sh > /var/log/raid_setup.log 2>&1